title: Paolo Brasolin | CV
description: Paolo Brasolin Curriculum Vitae

baseurl: "/cv"

compress_html:
  comments: ["<!-- ", " -->"]

exclude:
  - "Makefile"
  - "_tailwind/"
  - "_puppeteer/"
  - ".ruby-gemset"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "yarn.lock"
  - "postcss.config.js"
  - "tailwind.config.js"
  - "package.json"
  - "favicon.ico"
