#title: My Resume
#url: "https://paolobrasolin.github.io/cv"
#baseurl: "/cv"
#description: My resume
#encoding: "utf-8"

exclude:
  - "Makefile"
  - "_*/"
  - ".ruby-*"
  - "Gemfile*"
  - "node_modules/"
  - "yarn.lock"
  - "*.config.js"
  - "*.json"
