version: "3.7"

services:

  ruby: &ruby
    build:
      dockerfile: Dockerfile
      context: .
      target: ruby
    volumes:
      - .:/app
    profiles:
      - template

  node: &node
    build:
      dockerfile: Dockerfile
      context: .
      target: node
    volumes:
      - .:/app
    profiles:
      - template

  jekyll:
    <<: *ruby
    profiles: []
    ports:
      - "4000:4000"
      - "35729:35729"
    command: bundle exec jekyll serve --force_polling --livereload --host 0.0.0.0 --port 4000

  postcss:
    <<: *node
    profiles: []
    command: yarn run watch:css

