title: Service
body: |
  - Co-authored the new LaTeX template for the _Compositionality_ journal in 2023.
  - Technical support for the _SMS 2.0 -- One school, many languages_ conference in 2023.
  - Technical support for the _Learner Corpus Research Graduate Conference_ in 2023.
