title: Service
body: |
  - Technical volunteer for the colocated [ICALP](https://compose.ioc.ee/icalp2024/), [LiCS](https://lics.siglog.org/lics24/) and [FSCD](https://cs.ioc.ee/fscd24/) conferences in 2024.
  - Co-author of the upcoming LaTeX template for the [_Compositionality_](https://compositionality-journal.org/) journal in 2023.
  - Organising committee member for the [_Learner Corpus Research Graduate Conference 2023_](https://lcrgradconf2023.eurac.edu/).
  - Technical organiser for the [_One school, many languages (project SMS 2.0)_](https://sms-project.eurac.edu/conference/) conference in 2023.
